[tool.poetry]
name = "google-pubsub-emulator-python-async2"
version = "0.1.0"
description = ""
authors = ["Daniele Esposti <daniele.esposti@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
click = "~8.1.3"
google-api-core = "~2.8.2"
google-auth = "~2.9.0"
google-cloud-pubsub = "~2.13"
grpcio = "~1.47.0"

[tool.poetry.dev-dependencies]
mypy = "^0.961"
isort = "^5.10.1"
black = "^22.6"
pdbpp = "^0.10.3"
ipython = "^8.4.0"
safety = "^2.1.1"
flake8 = "^4.0.1"
autoflake = "^1.4"
grpc-stubs = "^1.24.10"
pyupgrade = "^2.34.0"
types-protobuf = "^3.19.22"
types-requests = "^2.28.6"
types-setuptools = "^57.4.18"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true
skip_glob = ".venv"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310"]
exclude = '''
/(
    \.git|.venv
)/
'''

[tool.mypy]
exclude = ".venv/"
check_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_subclassing_any = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true

[[tool.mypy.overrides]]
module = "google.auth.credentials"
ignore_missing_imports = true
