[tool.poetry]
name = "google-pubsub-emulator-python-async2"
version = "0.1.0"
description = ""
authors = ["Daniele Esposti <daniele.esposti@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
click = "~7.1.2"
google-api-core = "~1.31.5"
google-auth = "~1.35.0"
google-cloud-pubsub = "~2.9"
grpcio = "~1.43.0"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
isort = "^5.7.0"
black = "^21.12b0"
pdbpp = "^0.10.3"
ipython = "^7.31.1"
safety = "^1.10.3"
flake8 = "^3.9.0"
autoflake = "^1.4"
grpc-stubs = "^1.24.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
float_to_top = true
