[tool.poetry]
name = "google-pubsub-emulator-python-async2"
version = "0.1.0"
description = ""
authors = ["Daniele Esposti <daniele.esposti@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
click = "~8.1.3"
google-api-core = "~2.10.1"
google-auth = "~2.12.0"
google-cloud-pubsub = "~2.13"
grpcio = "~1.49.1"

[tool.poetry.dev-dependencies]
mypy = "^0.981"
isort = "^5.10.1"
black = "^22.8"
pdbpp = "^0.10.3"
ipython = "^8.5.0"
safety = "^2.2.0"
flake8 = "^5.0.4"
autoflake = "^1.6"
grpc-stubs = "^1.24.11"
pyupgrade = "^2.38.2"
types-protobuf = "^3.20.4"
types-requests = "^2.28.11"
types-setuptools = "^65.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true
skip_glob = ".venv"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310"]
exclude = '''
/(
    \.git|.venv
)/
'''

[tool.mypy]
exclude = ".venv/"
check_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_subclassing_any = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true

[[tool.mypy.overrides]]
module = "google.auth.credentials"
ignore_missing_imports = true
